export const CREATE_SOLUTION = "CREATE_SOLUTION";
export const EDIT_SOLUTION = "EDIT_SOLUTION";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_SOLUTION = "DELETE_SOLUTION";
export const GET_SOLUTIONS = "GET_SOLUTIONS";
export const GET_SOLUTION = "GET_SOLUTION";
export const GET_USER_SOLUTION = "GET_USER_SOLUTION";
export const GET_USER = "GET_USER";

export const GET_ERROR = "GET_ERROR";
export const POST_ERROR = "POST_ERROR";

export const CREATE_PROBLEM = "CREATE_PROBLEM";
export const GET_PROBLEMS = "GET_PROBLEMS";
export const GET_PROBLEM = "GET_PROBLEM";
export const GET_USER_PROBLEMS = "GET_PRGET_USER_PROBLEMSOBLEM";
export const EDIT_PROBLEM = "EDIT_PROBLEM";

export const CREATE_SOLUTION_PROBLEM = "CREATE_SOLUTION_PROBLEM";
