export const CREATE_SOLUTION = "CREATE_SOLUTION";
export const EDIT_SOLUTIONS = "EDIT_SOLUTIONS";
export const CREATE_COMMENT = "CREATE_COMMENT";
export const DELETE_SOLUTION = "DELETE_SOLUTION";
export const GET_SOLUTIONS = "GET_SOLUTIONS";
export const GET_SOLUTION = "GET_SOLUTION";
